version: '3.8'

name: n8n_evolution_whatsapp
services:
  postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - evolution_postgres:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - evolution-net


  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: unless-stopped
    ports:
      - 8091:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - evolution.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8091
    depends_on:
      - postgres
    networks:
      - evolution-net

  n8n:
    container_name: server_n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - evolution-net

volumes:
  evolution_postgres:
  n8n_data:
  evolution_instances:
  evolution_store:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge